// livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { Livro } from '../livro';
import { ControleLivrosService } from '../controle-livros.service';
import { ControleEditoraService } from '../controle-editora.service';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule
  ],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent implements OnInit {

  livros: Livro[] = [];

  constructor(
    private controleLivros: ControleLivrosService,
    private controleEditora: ControleEditoraService
  ) {}

  ngOnInit(): void {

    this.controleLivros
      .obterLivros()
      .then(resultado => {

        this.livros = resultado;
      });
  }

  obterNomeEditora(
    codEditora: number
  ): string {

    return this.controleEditora
      .getNomeEditora(codEditora);
  }

  excluir(
    codigo: string
  ): void {

    this.controleLivros
      .excluir(codigo)
      .then(() => {

        this.controleLivros
          .obterLivros()
          .then(resultado => {

            this.livros = resultado;
          });

      });
  }

}
<h1>Catálogo de Livros</h1>

<p>
  <a routerLink="/dados">
    Novo Livro
  </a>
</p>

<table border="1">

  <thead>
    <tr>
      <th>Título</th>
      <th>Editora</th>
      <th>Autores</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>

    <tr
      *ngFor="
      let livro of livros;
      let i = index
      "
    >

      <td>
        {{ livro.titulo }}
      </td>

      <td>
        {{
          obterNomeEditora(
            livro.codEditora
          )
        }}
      </td>

      <td>
        {{
          livro.autores.join(', ')
        }}
      </td>

      <td>

        <button
          (click)="
          excluir(
            livro.codigo
          )"
        >
          Excluir
        </button>

      </td>

    </tr>

  </tbody>

</table>

// livros-react/src/LivroLista.tsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { ControleLivros } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';
import { Livro } from './model/Livro';

export default function LivroLista() {

  const [livros, setLivros] = useState<Livro[]>([]);

  const controleLivros = new ControleLivros();
  const controleEditora = new ControleEditora();

  useEffect(() => {

    controleLivros
      .obterLivros()
      .then(resultado => {
        setLivros(resultado);
      });

  }, []);

  const excluir = (codigo: string) => {

    controleLivros
      .excluir(codigo)
      .then(() => {

        controleLivros
          .obterLivros()
          .then(resultado => {
            setLivros(resultado);
          });

      });
  };

  return (
    <div>

      <h1>Catálogo de Livros</h1>

      <Link to="/novo">
        Novo Livro
      </Link>

      <br />
      <br />

      <table border={1}>

        <thead>

          <tr>
            <th>Título</th>
            <th>Editora</th>
            <th>Autores</th>
            <th>Ações</th>
          </tr>

        </thead>

        <tbody>

          {livros.map((livro, index) => (

            <tr key={index}>

              <td>{livro.titulo}</td>

              <td>
                {controleEditora.getNomeEditora(
                  livro.codEditora
                )}
              </td>

              <td>
                {livro.autores.join(', ')}
              </td>

              <td>

                <button
                  onClick={() =>
                    excluir(livro.codigo)
                  }
                >
                  Excluir
                </button>

              </td>

            </tr>

          ))}

        </tbody>

      </table>

    </div>
  );
}
