// livros-react/src/LivroDados.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { Livro } from './model/Livro';

import { ControleLivros }
from './controle/ControleLivros';

import { ControleEditora }
from './controle/ControleEditora';

export default function LivroDados() {

  const navigate = useNavigate();

  const controleLivros =
    new ControleLivros();

  const controleEditora =
    new ControleEditora();

  const [titulo, setTitulo] =
    useState('');

  const [resumo, setResumo] =
    useState('');

  const [autores, setAutores] =
    useState('');

  const [codEditora, setCodEditora] =
    useState(1);

  const incluir = () => {

    const livro = new Livro(
      '',
      codEditora,
      titulo,
      resumo,
      autores
        .split('\n')
        .filter(a => a !== '')
    );

    controleLivros
      .incluir(livro)
      .then(() => {

        navigate('/');

      });
  };

  return (

    <div>

      <h1>Novo Livro</h1>

      <div>

        <label>Título</label>

        <br />

        <input
          value={titulo}
          onChange={(e) =>
            setTitulo(
              e.target.value
            )
          }
        />

      </div>

      <br />

      <div>

        <label>Resumo</label>

        <br />

        <textarea
          value={resumo}
          onChange={(e) =>
            setResumo(
              e.target.value
            )
          }
        />

      </div>

      <br />

      <div>

        <label>Autores</label>

        <br />

        <textarea
          value={autores}
          onChange={(e) =>
            setAutores(
              e.target.value
            )
          }
        />

      </div>

      <br />

      <div>

        <label>Editora</label>

        <br />

        <select
          value={codEditora}
          onChange={(e) =>
            setCodEditora(
              Number(
                e.target.value
              )
            )
          }
        >

          {controleEditora
            .getEditoras()
            .map(editora => (

              <option
                key={
                  editora.codEditora
                }
                value={
                  editora.codEditora
                }
              >
                {editora.nome}
              </option>

            ))}

        </select>

      </div>

      <br />

      <button
        onClick={incluir}
      >
        Salvar
      </button>

      <br />
      <br />

      <button
        onClick={() =>
          navigate('/')
        }
      >
        Voltar
      </button>

    </div>
  );
}

// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

import { Livro } from '../livro';

import {
  ControleLivrosService
} from '../controle-livros.service';

import {
  ControleEditoraService
} from '../controle-editora.service';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [
    FormsModule,
    CommonModule
  ],
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent {

  titulo = '';

  resumo = '';

  autores = '';

  codEditora = 1;

  editoras: any[] = [];

  constructor(
    private router: Router,
    private controleLivros:
      ControleLivrosService,
    private controleEditora:
      ControleEditoraService
  ) {

    this.editoras =
      this.controleEditora
        .getEditoras();
  }

  incluir() {

    const livro = new Livro(
      '',
      this.codEditora,
      this.titulo,
      this.resumo,
      this.autores
        .split(',')
        .map(a => a.trim())
    );

    this.controleLivros
      .incluir(livro)
      .then(() => {

        this.router
          .navigateByUrl(
            '/lista'
          );

      });
  }
}
<h1>Novo Livro</h1>

<p>

  <label>
    Título
  </label>

  <br>

  <input
    [(ngModel)]="titulo"
  >

</p>

<p>

  <label>
    Resumo
  </label>

  <br>

  <textarea
    [(ngModel)]="resumo"
  >
  </textarea>

</p>

<p>

  <label>
    Autores
  </label>

  <br>

  <input
    [(ngModel)]="autores"
  >

</p>

<p>

  <label>
    Editora
  </label>

  <br>

  <select
    [(ngModel)]="codEditora"
  >

    <option
      *ngFor="
      let editora
      of editoras
      "
      [value]="
      editora.codEditora
      "
    >

      {{
      editora.nome
      }}

    </option>

  </select>

</p>

<button
  (click)="incluir()"
>
  Salvar
</button>

<br><br>

<a routerLink="/lista">
  Voltar
</a>
